### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by AlexisBarta** [typhonjs/backbone-parse-es6#1]
I had to define `jQuery` like that `var jQuery = $;` to make my other javascript with jQuery dependency work.

**Comment by typhonrt** [comment]
I take it that you are using the global inclusive bundle? If that is the case then I just added the jQuery global export as well as $ and made new bundles. It's defined here:
https://github.com/typhonjs/backbone-parse-es6/blob/master/src/GlobalInclusiveRuntime.js#L20

This is for the `backbone-parse-inclusive.js` global bundle, so grab a new version from the master branch and let me know if this fixes the issue.

**Comment by AlexisBarta** [comment]
Yes I'm using `backbone-parse-inclusive.min.js` I forgot to mention. Oops.

It's definitely working now! Thanks ;)

**Comment by typhonrt** [comment]
No problem.. Thanks for checking things out! It's nice to be able to use the latest Backbone API w/ Parse.

**Comment by AlexisBarta** [comment]
Yes it's! Thanks for the great work ;)

**Comment by typhonrt** [comment]
Check out https://github.com/typhonjs-demos for some basic demos of using things w/ ES6 source and SystemJS / JSPM. I'll also be rounding out the rest of the demos showing RequireJS (old example / SystemJS is way better) and global usage. I do have to get some documentation for the demos up though this week after finishing a few of them off.
