### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by AlexisBarta** [typhonjs/backbone-parse-es6#2]
> API documentation can be found in the docs/ directory and online here: http://js.docs.typhonrt.org/backbone-parse-es6/

The url should be http://js.typhonrt.org/docs/backbone-parse-es6/

**Comment by typhonrt** [comment]
Thanks for the heads up. I just posted the latest docs at the proper link (http://js.docs.typhonrt.org/backbone-parse-es6/)

**Comment by AlexisBarta** [comment]
Perfect ;) You're welcome.
