### ISSUE TITLE
ParseCollection fetch issue

### ISSUE THREAD

**Issue by AlexisBarta** [typhonjs/backbone-parse-es6#3]
Hi,

It's me again, long time no see. When I `fetch` a ParseCollection the `models` array has the expected number  of ParseObject (which is 5 in my case) but they are all empty (no id, no attributes) even if I can see that the http request work successfully. Do you have any idea why?

``` javascript
// path/models/MyModel.js

'use strict';

import Backbone from 'typhonjs/backbone-parse-es6';

export default class MyModel extends Backbone.Model
{
   /**
    * Returns the `className` which is the table stored in Parse.
    *
    * @returns {string}
    */
   get className() { return 'MyModel'; }
}
```

``` javascript
// path/collections/MyCollection.js
'use strict';

import Backbone from 'typhonjs/backbone-parse-es6';
import MyModel from 'path/models/MyModel.js';

class MyCollection extends Backbone.Collection
{
   /**
    * Reference to this collection's model.
    *
    * @returns {MyModel}
    */
   get model() { return MyModel; }
}

/**
 * Exports an instance of MyCollection.
 */
export default new MyCollection();
```

``` javascript
// path/App.js

import Backbone from 'typhonjs/backbone-parse-es6';
import _ from 'underscore';

import myCollection from 'path/collections/MyCollection.js';

myCollection.query = new Parse.Query(myCollection.model);
myCollection.query.descending("createdAt");
myCollection.query.limit(5)
myCollection.fetch().then(function(){
     console.log(myCollection.models); //Show an array of 5 empty MyModel ParseObject
});
```

**Comment by typhonrt** [comment]
Hah... You actually caught me still up coding.. ;P  

I uploaded a full test case here showing that things are working correctly insofar as a JSPM / SystemJS install is concerned:
http://js.demos.typhonrt.org/typhonjs-issues-demos/repos/backbone-parse-es6/src/issue3/

I added an `Issue3` class output data from the `Text` column via jQuery to a `<ul>` and on the console. 

I am not sure about your execution environment. Previously I believe you were using the global bundle, so I assume you are looking into ES6 now? The above demo and the other canonical TODOs demos show usage w/ JSPM / SystemJS. The code is not that different from what you listed. In the coming week or so I will be getting up detailed tutorials. For the issue 3 demo above I copied your Model / Collection classes verbatim except changing things to `import Backbone from 'backbone';` which is how things are mapped w/ JSPM in the following file:
http://js.demos.typhonrt.org/typhonjs-issues-demos/repos/backbone-parse-es6/package.json

I changed a few things in the main entry JS file such as importing Parse via `import Parse from 'parse';` which is pertinent, but these changes are idiomatic to the JSPM environment:
http://js.demos.typhonrt.org/typhonjs-issues-demos/repos/backbone-parse-es6/src/issue3/main.js

Take note of the inclusion of `import 'parseinit'` which is a module that automatically initializes the Parse API keys via a separate config file holding the keys. It is mapped in package.json to:
http://js.demos.typhonrt.org/typhonjs-issues-demos/repos/backbone-parse-es6/jspm_packages/github/typhonjs/typhonjs-core-parse-init@master/src/lifecycle/ParseInitialize.js
and there are is a further mapped path, `'parseconfig'` there to load the API keys which is configured in additional config loading that occurs in index.html, but found here:
http://js.demos.typhonrt.org/typhonjs-issues-demos/repos/backbone-parse-es6/src/issue3/config/config-app-paths.js

If you don't include this you'll have to initialize the Parse API before usage manually. I also made things an ascending query and used jQuery (actually Zepto) to append `<li>` elements to a list.

**Comment by typhonrt** [comment]
Err... Yes.. I added the live demo and docs links to all the TODOs demos that are fully posted.  I'm actually almost done with Backbone->MeteorJS integration which is quite exciting... Way better than Parse! ;)

**Comment by AlexisBarta** [comment]
Thank you for your quick reply! Everything you do is great! 

Yes you caught me I was using the global bundle first and then I wanted to try ES6 (much better readability and organization of the code!). I'll take a serious look at everything you gave me and keep in touch ;)

I'll take a look at Meteor JS as well. Never heard of it before. Why do you think it's better than Parse?

Keep up the good work!

**Comment by typhonrt** [comment]
Well I'm ignoring all the client side of Meteor, but using the server setup and its great to run a complete server development environment instantly with free deployment testing options as well. IE one controls the complete server / client setup. I'm using the DDP protocol over WebSockets to perfect a project I forked (Asteroid) converting it to ES6 and making it rock solid then hooking things up to Backbone. You don't have to fetch anything as subscription is over a continuous connection. You can have reactive queries which auto-sync which is something I'm going to try and make fit seamless w/ Backbone. 

Not everything is great with Meteor. I don't like how they force their process on you for the client side; it's a little too opinionated. If you went and looked at any tutorials it would be focusing on the client stuff. If I was able to use JSPM / SystemJS and create a single executable bundle that would be neat, but it's messed up IMHO. But one can still host the client web app part anywhere and just use the server capabilities of Meteor which is currently running on MongoDB.

Of note I added a local query system for collections that is above and beyond Backbone to `backbone-parse-es6` and soon `backbone-meteor-es6`. :D You can use MongoDB styled queries on the client side from any collection for sorting. It's really handy to be able to store queries in JSON. Check the docs, but some of the methods are "find", "findOne" & "whereBy". I have a very slick table component that is searchable / sortable that loads from a JSON description of the data using the client side query functionality.

If you want to check out ES6 definitely give JSPM / SystemJS a try. Once you get a hang of it you'll never want to go back to the 'global' side of things. 

I'll close this issue though. It might be a week or so until I have all the tutorials up, but the code is there w/ basic build instructions which aren't too bad if you already have been using Node & npm.

**Comment by typhonrt** [comment]
Just as a note.. I've created a separate `typhonjs-issues-demos` repo for demos regarding issues surrounding TyphonJS repos including `backbone-parse-es6`. I've updated the links in the above comments, but you can find the live demo here:
http://js.demos.typhonrt.org/typhonjs-issues-demos/repos/backbone-parse-es6/src/issue3/

and all issues related demos here:
http://js.demos.typhonrt.org/typhonjs-issues-demos/repos/backbone-parse-es6/

documentation here:
http://js.demos.typhonrt.org/typhonjs-issues-demos/repos/backbone-parse-es6/docs/
