### ISSUE TITLE
Dependency Version Updates

### ISSUE THREAD

**Issue by typhonrt** [typhonjs/backbone-parse-es6#4]
All bundles and documentation have been updated for Parse 1.6.12 support.

**Comment by typhonrt** [comment]
All bundles and documentation have been updated for Parse 1.6.14 support.

**Comment by typhonrt** [comment]
New bundles have been generated in `./dist`. There is now a UMD bundle as well since SystemJS Builder 0.15.0+ supports UMD including support for [rollup](http://rollupjs.org/) for bundling which gives a slightly smaller bundle size. Also jquery 2.2.0 is now supported in the global inclusive bundles. 

If you grabbed a bundle in the last 1.5 weeks please get the latest as there were a couple of issues when upgrading to SystemJS Builder 0.15.0+ which I just resolved. For those curious here are the relevant issues filed with SystemJS Builder:
https://github.com/systemjs/builder/issues/470
https://github.com/systemjs/builder/issues/471

As always please file a new issue if there are any problems with any of the bundles...

**Comment by typhonrt** [comment]
The latest Parse 1.7.0 has been integrated with backbone-parse-es6. New bundles are available in [dist](https://github.com/typhonjs-parse/backbone-parse-es6/tree/master/dist). I've contributed patches to SystemJS Builder for fixes mentioned in the previous message which have been released in JSPM 0.16.25 which also is updated in backbone-parse-es6 & all demo repos. There are a few new rhetorical global JS demos and I will be adding a RequireJS example tomorrow. These are meant to help folks move from global or RequireJS to the modern ES6 JSPM / SystemJS method of consuming all TyphonJS repos. 

The most exciting addition though is that [Electron](http://electron.atom.io/) support has been added to [typhonjs-core-gulptasks](https://www.npmjs.com/package/typhonjs-core-gulptasks) and there is a new demo that shows how easy it is to create a desktop app from the bundled backbone-es6-localstorage-todos web app at [electron-backbone-es6-localstorage-todos](https://github.com/typhonjs-demos/electron-backbone-es6-localstorage-todos). It's really easy to create desktop apps from existing browser based web apps with the integrated Gulp tasks. This is a glimpse into the future for `backbone-parse-es6`. As things go right now Electron executes things in a Node environment and as things go the `backbone-parse-es6` bundles / libraries complain about not being in a browser context. So right now you can't use `backbone-parse-es6` to create an Electron desktop app.. 

All is not lost though as the next major version of JSPM / SystemJS will support Node & browser deployment environments and within a month or so once JSPM 0.17.x is more stable and exits beta `backbone-parse-es6` will be updated with dual Node / browser library versions in addition to an Electron desktop example. For now though check out the `backbone-es6` version for a taste of what is to come.

**Comment by typhonrt** [comment]
Great news folks! I was able to get Parse to play nice with Electron, so it's now possible to create Electron desktop apps with backbone-parse-es6.  So go checkout [electron-backbone-parse-es6-todos-improved](https://github.com/typhonjs-demos/electron-backbone-parse-es6-todos-improved) and get started on making crossplatform web and desktop apps from the same codebase!

For more details on what the problem was you can view [Parse Issue 193](https://github.com/ParsePlatform/Parse-SDK-JS/issues/193).

**Comment by AlexisBarta** [comment]
I never played with Electron yet but that seems awesome. You always do a great job ;) Too bad that Parse is closing his service :s

**Comment by typhonrt** [comment]
Give the Electron demo a try. It's pretty straight forward and doesn't require a lot of code. I'm really impressed with Electron as I was able to integrate it without much overhead via typhonjs-core-gulptasks. It's approaching 1.0 and seems to be a solid option. 

Re: Parse. That is too bad, but after getting backbone-parse-es6 working I started immediately on backbone-meteor-es6 which I'll be releasing soon, so there is an option to switch to Meteor soon and continue using modern Backbone / ES6 w/ a solid tool chain external to Meteor itself for the client side. I may look at also supporting Firebase and a straight up MEAN stack or equivalent in time. I also have my own startup efforts to continue as well of course.

At least Parse is open sourcing the majority of the infrastructure for self hosting. It'd be nice if they open up the data browser / management code. So, backbone-parse-es6 should still have some future use. 

As far as I was concerned w/ 1.6 and the unceremonious chop of Backbone from the API is when Parse lost me and it was time to move on despite putting out backbone-parse-es6.

**Comment by AlexisBarta** [comment]
I don't know yet what will be my next move. I'll give a better look at Meteor because I don't feel like developing a backend.

Yeah Parse was definitely not the best for explanations... as the shutdown happening all of sudden proves it.

**Comment by typhonrt** [comment]
Well you do develop server side code / have more control of things w/ Meteor. If you do look into Meteor you are not going to find a lot of good info on the way I'm at least approaching things. 
I don't like Blaze, their client side solution, and the all in one build process which is no where near as powerful as JSPM / SystemJS. With backbone-meteor-es6 you'll be able to fully control the client side build w/ JSPM / SystemJS and can use the Meteor tooling to just create the server side. I may also take a look at supporting another hosted solution though. The `backbone-<X>-es6` libraries are nice as there is more or less not too many changes when swapping things out between providers.

**Comment by typhonrt** [comment]
New distribution bundles are available in `./dist` with Parse 1.7.1 and jQuery 2.2.1 updates. And full serialization / deserialization support is now available for Models that reference parse pointers. Please see description at end of Issue #5.

**Comment by typhonrt** [comment]
backbone-parse-es6 is now at parity with Backbone 1.3.3. New `./dist` bundles have been generated and Parse has been updated to 1.8.4 and jQuery has been updated to v2.2.3 in the global inclusive bundle.

**Comment by typhonrt** [comment]
New ./dist bundles have been generated and Parse has been updated to 1.8.5 for the global inclusive bundle.
